### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by TomRomeo** [phiresky/timetrackrs#2]
Heya, this looks really cool and promissing for a time tracker app! :)
Can you tell me how to build it? I am not quite sure and didn't find any build instructions.

Thanks!

**Comment by phiresky** [comment]
Hey.

It's not really ready for use yet. The data collection works for the implemented sources, but the UI is unfinished. 

You can build / install it using

```bash
git clone https://github.com/phiresky/timetrackrs.git
cd timetrackrs
cd frontend
yarn install
yarn build
cd ..
cargo install --path .
```

**Comment by phiresky** [comment]
I've added build instructions and a note to the readme.
