### ISSUE TITLE
where is the data stored? in the .local/timetrackr/*.sqlite files?

### ISSUE THREAD

**Issue by emilBeBri** [phiresky/timetrackrs#27]
Hi maybe it's just me, but where is the data stored?  is there an easy way to convert it to csv? I know it's not an  efficient format, but it's easier for me to grasp (and then get an idea of wether this tool is as useful as it looks! great job)  

(if the question is too noob, just say so, I can accept that a tool requires a certain level of knowledge to even use :) )

**Comment by phiresky** [comment]
yes, the raw captured data is stored in raw_data and the processed data
(after applying the rules) is stored in processed. I can recommend
SqliteBrowser to explore the data or export to CSV.
