### ISSUE TITLE
timeline counts with no end

### ISSUE THREAD

**Issue by Frank-Buss** [phiresky/timetrackrs#5]
I just clicked a bit in the webapp between Dashboard and Timeline, and now it counts without end in the Timeline window:
https://www.youtube.com/watch?v=5Ny_Ct4oNsg

**Comment by phiresky** [comment]
It's probably broken in two ways

1. the css is broken which causes the auto-load on scroll to trigger more than it should
2. i changed the data format that the data is sent to the frontend, but haven't adjusted the timeline view yet

**Comment by phiresky** [comment]
should be fixed now
